### ISSUE TITLE
Support upload of rules as jar files

### ISSUE THREAD

**Issue by LumnitzF** [seaside1/jrule#10]
If I understand the current approach correctly, I have to upload my uncompiled rules as java files into the target directory, where they are compiled into class files. However, I would like to compile the files locally, and only upload the final jar file to the openhab instance. 
Some benefits:

- I can use for example annotation processors (e.g. lombok)
- I can package my dependencies directly into the jar, and don't need to upload them separately (allows also different dependencies for different rule-sets)
- I can upload the final jar using for example a maven goal, and don't have to do it manually

If you would be willing to integrate this feature, but don't have the time or are simply not in the mood for it, I would be willing to provide a PR.

**Comment by seaside1** [comment]
Hi!

Sounds like a good suggestion, as long as the "old way" is still supported. I would very much welcome a PR, it's good to get more people involved.

Regards, S

**Comment by seaside1** [comment]
I've fixed this, see commit:
https://github.com/seaside1/jrule/commit/3786fd1949a57d18e0a6b6b985c00654c8f62bbd

Please try it out and if needed reopen the issue.

BR S

**Comment by No3x** [comment]
I tested it and it looks good. I created a sample gradle repo configured to work with the current approach. It creates a jar at the right place to be picked up by jrule.
https://github.com/No3x/jrule-gradle-jar
