### ISSUE TITLE
Adding @JRuleDebounce(10)

### ISSUE THREAD

**Issue by querdenker2k** [seaside1/jrule#101]
@seaside1 What do you think about adding getTimedLock (additionally) to method annotations like @JRuleDebounce(10)?
The time will be in seconds (as float).

**Comment by seaside1** [comment]
Very good idea! 👍

**Comment by querdenker2k** [comment]
add to this MR: https://github.com/seaside1/jrule/pull/100

**Comment by seime** [comment]
Merged
