### ISSUE TITLE
Adding Metadata, Groups and Tags to JRuleItem

### ISSUE THREAD

**Issue by querdenker2k** [seaside1/jrule#105]
I already started adding getMetadata, getTags and getGroups to JRuleItem.
But i am not sure how to implement this.
2 options
- Add the values to all JRuleItem constructors. (Will be cached in JRuleItemRegistry with the items) -> Maybe faster at runtime because the values must not be read from the openhab runtime.
- Just create getters and inside them fetch the data from the openhab runtime.

@seime @seaside1: What do you think?

**Comment by seime** [comment]
If we cache the values ourselves, we must be sure we get notified by the runtime whenever the data changes. Maybe we get this notification already as part of ItemUpdatedEvent (or whatever it is called).

Other than that I do not have any strong opinions.

**Comment by querdenker2k** [comment]
I though the metadata would be updated because JRuleItems class will be regenerated. This would be enough, right?

**Comment by seime** [comment]
Yes I would think so

**Comment by querdenker2k** [comment]
added #121

**Comment by seime** [comment]
Closed via #121
