### ISSUE TITLE
JDK required

### ISSUE THREAD

**Issue by No3x** [seaside1/jrule#11]
This tool requires JDK for the `javax.tools.JavaCompiler` attempted to load via `javax.tools.ToolProvider.getSystemJavaCompiler()`.

<details>
  <summary>Diagnostics</summary>
  
 I found this by tracking it down with the log files:
```
2021-12-30 12:03:35.991 [INFO ] [.jrule.internal.handler.JRuleHandler] - [JRuleHandler] Compiling items
2021-12-30 12:03:35.997 [DEBUG] [rule.internal.compiler.JRuleCompiler] - [+JRuleCompiler+] Compiling items in folder: /etc/openhab/automation/jrule/items/org/openhab/automation/jrule/items/generated
2021-12-30 12:03:36.004 [DEBUG] [rule.internal.compiler.JRuleCompiler] - [+JRuleCompiler+] ClassNameSetSize: 0
```
The last thing I see is `ClassNameSetSize: 0`. Looking to the code the next thing I should see is `Compiling classes using classpath:` https://github.com/seaside1/jrule/blob/70a2b2d43dea8245597f0c3d477bffd95f96ce5b/src/main/java/org/openhab/automation/jrule/internal/compiler/JRuleCompiler.java#L115 but this is not executed. The only lines that can cause this are therefore
https://github.com/seaside1/jrule/blob/70a2b2d43dea8245597f0c3d477bffd95f96ce5b/src/main/java/org/openhab/automation/jrule/internal/compiler/JRuleCompiler.java#L109-L111
Also the next "step" `Creating items jar`  is not logged.
  
</details>

Turns out that [`ToolProvider.getSystemJavaCompiler()`](https://github.com/seaside1/jrule/blob/70a2b2d43dea8245597f0c3d477bffd95f96ce5b/src/main/java/org/openhab/automation/jrule/internal/compiler/JRuleCompiler.java#L110)  returns null.
https://github.com/seaside1/jrule/blob/70a2b2d43dea8245597f0c3d477bffd95f96ce5b/src/main/java/org/openhab/automation/jrule/internal/compiler/JRuleCompiler.java#L110
I had adoptopenjdk-11-hotspot-**jre**-armhf installed which does not include the required class. -> Fix: install a JDK.

Maybe you can add a check for null or for JDK, a note in the readme or this issue is sufficient for documentation.

**Comment by seaside1** [comment]
Good suggestion. I'll do a check for it when the binding starts.

**Comment by seaside1** [comment]
https://github.com/seaside1/jrule/commit/39b467cbdac0b754061d11f09b532a984c96557c
