### ISSUE TITLE
New dependency on openhab core needed when developing rules

### ISSUE THREAD

**Issue by seaside1** [seaside1/jrule#112]
the

 ```java
public interface JRuleValue {
    String toString();

    String stringValue();

    Command toOhCommand();

    State toOhState();
}
```

Has introduced dependency on openhab  core when developing rules. I initially tried to avoid this to make it simpler for the user developing rules having as few deps as possible when developing rules.

I think we lost some simplicity here when you previously could do:

`        Double eventDoubleValue = event.getState().getValueAsDouble();
`

I guess we could either add more JRuleValue implementations to support those type (Double etc), or we could wrap and avoid using core. Possibly we should extract the openhab core deps in the jrule-jar so it is simple for the user to setup development.

Any thoughts @querdenker2k  @seime ?

**Comment by seime** [comment]
I'm currently looking at specifying Units in the QuantityType (currently a String), and this would also pull openhab deps into the user rule project.

I do not think it is a problem as long as we can provide the user with a good starting point/project template/maven project/gradle project and well defined (and few) instructions on how to get started.

**Comment by seaside1** [comment]
https://github.com/seaside1/jrule/pull/115
