### ISSUE TITLE
JRuleWhenItemChange not working with generated item values

### ISSUE THREAD

**Issue by seaside1** [seaside1/jrule#113]
```java
    @JRuleWhenItemChange(item = _Contact.ITEM, from = _Contact.OPEN, to =_Contact.CLOSED)
```

This yields a compilation error "the value for annotation attribute must be a constant expression"

Cause of this is JRuleContactItem.java
Where we have

```java
public interface JRuleContactItem extends JRuleItem {
    String OPEN = JRuleOpenClosedValue.OPEN.stringValue();
    String CLOSED = JRuleOpenClosedValue.CLOSED.stringValue();
```

This is not possible in compile time, they have to be changed to:
```java
public interface JRuleContactItem extends JRuleItem {
    String OPEN = "OPEN";
    String CLOSED = "CLOSED"
```

**Comment by seaside1** [comment]
https://github.com/seaside1/jrule/pull/114

**Comment by seime** [comment]
I think it works if you instead use

```
@JRuleWhenItemChange(item = JRuleItemNames._Contact.ITEM, from = JRuleContactItem.OPEN, to = JRuleContactItem.CLOSED)
```

I also include a `Names` inner class in my private enums in order to use them inside annotations, ie 
```
@JRulePrecondition(item = JRuleItemNames.MyItem, condition = @JRuleCondition(eq = BedroomMode.Names.DAY))
```

```
public enum BedroomMode {
    DAY(Names.DAY),
    NIGHT(Names.NIGHT);

    public class Names {
        public static final String DAY = "DAY";
        public static final String NIGHT = "NIGHT";
    }

    private final String label;

    BedroomMode(String label) {
        this.label = label;
    }

    @Override
    public String toString() {
        return label;
    }
}
```

**Comment by querdenker2k** [comment]
@seaside1 Is here something to do or is it working for you?

**Comment by seaside1** [comment]
This works. The drawback as I see it that it requires some knowledge from the user to decide the correct type when setting up the rules. Previously you could just use your "item" and get the correct type from there.

**Comment by querdenker2k** [comment]
Previously it was the same doing.
When using a state for a trigger you have to use the value from JRuleXXXItem and when you want to send a command you have to use the JRuleValue.
It's sad that JRuleValue cannot be used by the compiler in annotations.

@seaside1 Do you have any suggestions to do it better or can this be closed for now?
