### ISSUE TITLE
Item class generation broken

### ISSUE THREAD

**Issue by seaside1** [seaside1/jrule#116]
The class per item is no longer generated it seems.

It's not generated in JRuleItemClassGenerator anymore.

**Comment by seaside1** [comment]
I guess this was something that was introduced with #85  . I didn't notice because I didn't clean out my generated class files in the folder manually.

**Comment by seime** [comment]
Should probably include some info in the changelog about manually cleaning the `gen` folder before upgrading.

**Comment by querdenker2k** [comment]
Couldn't we clear the gen folder automatically before regenerating something.

**Comment by seaside1** [comment]
Yes we should try and clear it automatically. We don't want to always clear it. Ie if nothing is change it should not be deleted thus avoid unnecessary writes to the disk.

**Comment by seime** [comment]
In general clearing all files I think will lead to longer compilation time as well.

For the items package we only expect 2 files now, so we can in *this* case delete all other files. Clearing all things and actions would be costly for people on slow hardware.

**Comment by querdenker2k** [comment]
In generell it's working because all changed files will be update. The problem just occured because the change of the Item generation doing.
So it's just a migration issue.
I think we could close this?

**Comment by seaside1** [comment]
I agree, closing.
