### ISSUE TITLE
Flaky tests or startup sequence

### ISSUE THREAD

**Issue by seime** [seaside1/jrule#149]
There is some flakyness in the integration tests. Builds fail randomly. See build 308 and 309 for example, the latter is just another re-run of the previous.

Not sure whether the tests are to blame, or if we have something to fix regarding JRule startup behaviour (I often see a second recompilation/reload triggered after starting - for no apparent reason)

**Comment by querdenker2k** [comment]
the problem happens because of this error:
`com.influxdb.exceptions.InternalServerErrorException: unexpected error writing points to database: field type conflict`
will create a merge request to get rid of this (or reduce this).

**Comment by seime** [comment]
Possibly fixed by #151 , leaving open a bit longer to see if server build stabilizes.
