### ISSUE TITLE
isTimerRunning("blabla") returns always true on 4.x.x

### ISSUE THREAD

**Issue by rdrxr** [seaside1/jrule#156]
running OpenHAB 4.0.0-SNAPSHOT - Build #3482 with current JRULE 4.x.x Branch (v4.0.0.202305140838)

JRULE Build was taken from https://github.com/seaside1/jrule/actions/runs/4971448181

Problem may also be with my setup somewhere, am still Java beginner.

**Comment by querdenker2k** [comment]
yes you're right, that's a bug. will fix this.
