### ISSUE TITLE
MDC tags not working anymore

### ISSUE THREAD

**Issue by querdenker2k** [seaside1/jrule#197]
No MDC tagging is possible anymore. I think it's broken with the dynamic rule stuff?

**Comment by seaside1** [comment]
Not sure, unfortunately I'm not using MDC tags atm. Probably something we should fix before next release.

**Comment by seaside1** [comment]
I'll see if I can set it up again and test.

**Comment by seaside1** [comment]
@rsopp Can you help to check this? I can't see anything apparent in the dynamic build PR, to me the MDC-tags looks similar as before

**Comment by seaside1** [comment]
Adding 
 ` @JRuleTag(value = "TESTTAG")
`
On a testrule, and adding
```
    JRuleLog.debug(logger, context.getLogName(), "setting mdc tags: {}", context.getLoggingTags());
            Arrays.stream(context.getLoggingTags()).forEach(tag -> logInfo("mdc: using tag in context: {}", tag));

```

The tag seem to be stick when executing the rule:
2024-03-20 20:40:27.985 [INFO ] [on.jrule.internal.engine.JRuleEngine] - [JRuleEngine] mdc: using tag in context:  TESTTAG

I'm in the process of setting up Graylog, so not using kibana/logstash atm. Maybe you can confirm between what commits the errors occurs @querdenker2k

**Comment by querdenker2k** [comment]
no sorry, it's not all MDC tags. just the rule mdc tag is missing.

**Comment by querdenker2k** [comment]
haven't looked properly on monday. created a MR for the fix.

**Comment by rsopp** [comment]
> haven't looked properly on monday. created a MR for the fix.

Thanks for fixing. Seems I have overseen this..

**Comment by seime** [comment]
Can this issue be closed?

**Comment by querdenker2k** [comment]
Yes, please

Am 10. Juli 2024 12:47:46 schrieb Arne Seime ***@***.***>:
