### ISSUE TITLE
Unable to trigger rule from rest call

### ISSUE THREAD

**Issue by vpant** [seaside1/jrule#209]
When I issue a request to /rules/{ruleUID}/runnow I am getting a 200 ok response but the rules is not triggered. 

I have tested triggering the rule with `@JRuleWhenItemChange` and it worked so this not a logical error.

**Comment by seaside1** [comment]
Yes, JRule does not support triggering the rules from UI (Play button). Calling the rest API to trigger a rule would be the same. The Rules are only triggered by events on the event-bus.
I hope we can add support both in UI and via Rest to trigger rule, but not possible at the moment
