### ISSUE TITLE
Generated classes in beta-8 invalid

### ISSUE THREAD

**Issue by gerrieg** [seaside1/jrule#32]
You can test it with the _MyTestSwitch class:
```
Static method 'getState()' in 'org.openhab.binding.jrule.items.generated._MyTestSwitch' cannot override instance method 'getState()' in 'org.openhab.automation.jrule.items.JRuleSwitchItem'
```

**Comment by seaside1** [comment]
Yes, was a bit too quick will do a temporary rollback and fix the issue in beta9, thanks.

**Comment by seaside1** [comment]
Fixed in beta9 by changing name. 
I think we have to decide in the long run if we want this to work from a static perpective or not with items.
