### ISSUE TITLE
Additional issues with pr42 merge

### ISSUE THREAD

**Issue by seaside1** [seaside1/jrule#44]
I've noticed some intermittent failures for
- Log name used in logs (not always the correct rule)
- send command to GroupSwitchItem via JRuleItems sometimes fail in a nullpointer (all subsequent members are ignored)
- JRuleSwitchItems invoked by JRuleItems sometimes fail, where as using sendCommand(itemName, JRuleOnOffValue value) works.

**Comment by seaside1** [comment]
Fixed sendCommand and postUpdate for groups:

https://github.com/seaside1/jrule/commit/97647bf145d2567d31c03491d189cc2ca3bac5b9

**Comment by seaside1** [comment]
Missed changing name in compiler:

https://github.com/seaside1/jrule/commit/41045532ed91d610da61ba971e8873a4b1cc9bc4

**Comment by seime** [comment]
Do you have some stacktraces of the 2 last ones?

**Comment by seaside1** [comment]
I've fixed them with this commit: https://github.com/seaside1/jrule/commit/97647bf145d2567d31c03491d189cc2ca3bac5b9
I still see some group issues trying to figure out if it is my rules or the rules.

**Comment by seaside1** [comment]
I think groups are working ok now as far as I can tell.

**Comment by seime** [comment]
Could you elaborate on issue no 1?

**Comment by seaside1** [comment]
Not sure. I saw this in one of my rules which had the incorrect logname (it had the logname of another rule defined in another file), could be a threading issue, or it could have been caused by another issue (like the group thing). I'll try to see if it happens again, otherwise it is working :)

**Comment by seaside1** [comment]
Closing this one since I can't reproduce.
