### ISSUE TITLE
Split JRuleWhen into multiple triggers

### ISSUE THREAD

**Issue by querdenker2k** [seaside1/jrule#53]
I would suggest to split JRuleWhen into multiple triggers, like JRuleWhenTime, JRuleWhenItem and JRuleWhenChannel to not have such a lot unused annotation functions.
What do you think @seaside1 @seime

**Comment by seime** [comment]
👍

**Comment by seaside1** [comment]
Yes, but maybe we can start with adding these new JRuleWhenXXXX and keep the old one as well. That way we don't break existing rules for people. It also gives more time to test before removing JRuleWhen (if we decide to do so).

**Comment by querdenker2k** [comment]
I removed the old JRuleWhen because multiple options will let the code be more confusing.

**Comment by seaside1** [comment]
Closing after merge of https://github.com/seaside1/jrule/pull/61
