### ISSUE TITLE
Timer parsing broken

### ISSUE THREAD

**Issue by seime** [seaside1/jrule#69]
If you define this rule

## Example 31

Use case: Restart thing every night due to binding flakyness

```java
@JRuleName("Restart thing every night")
@JRuleWhenTimeTrigger(hours=3)
public void restartThing() {
    JRuleThings.my_flaky_thing.restart();
}
```

then the current cron generated will be `* * 3 * * *` which will cause the timer to go off _continously_ from 3 to 4 in the morning

**Comment by seime** [comment]
@querdenker2k

**Comment by querdenker2k** [comment]
I don't really understand. What is not working?

**Comment by querdenker2k** [comment]
i got it now.
* * 3 * * * should be 0 0 3 * * *

**Comment by querdenker2k** [comment]
fixed here: https://github.com/seaside1/jrule/pull/70
@seime you have an idea how to test this automatically?

**Comment by seime** [comment]
Sorry for the late response. 

Things we could test: 

- cron parsing -> extract to testable method
- have not found a way to create mocks that also mocks the annotations, maybe it require a bit of nasty relflection/class generation mumbo-jumbo
