### ISSUE TITLE
Dimmer items getState() returns value divided by 100

### ISSUE THREAD

**Issue by seime** [seaside1/jrule#7]
A Dimmer item typically has a PercentType as state.

When Doing JRuleDimmerItem.getState() this value is converted from PercentType to DecimalType which effectively divides the value by 100.  So a dimmer value of 50 then is converted to 0.5 which is lost during conversion to int

**Comment by seaside1** [comment]
Nice, I haven't seen this myself. I guess your own fix, fixes the issue.
