### ISSUE TITLE
Why createTimer uses a Consumer instead of a Runnable

### ISSUE THREAD

**Issue by querdenker2k** [seaside1/jrule#78]
Are there any special needs why the createTimer functions uses a Consumer with an used Void parameter istead of a Runnable?
Otherwise I would change this to Runnable

**Comment by seime** [comment]
I also find the existing approach kinda difficult to follow, especially when working with #79 . I'd prefer if we were able to pass necessary context information in the Runnable instead of setting and clearing thread locals multiple places.

**Comment by seaside1** [comment]
Besides code being difficult to follow is there anything else that favors runnable? Async completable futures should have less over head, being nicer to the jvm. Not completely sure how the fork join pool works with openHAB runtime.

**Comment by querdenker2k** [comment]
Will be fixed here: https://github.com/seaside1/jrule/pull/100

**Comment by seime** [comment]
Merged
