### ISSUE TITLE
Cleanup Item generation

### ISSUE THREAD

**Issue by querdenker2k** [seaside1/jrule#84]
I want (and currently doing) two things:
- Do not generate a custom Item class for every Item. Sometimes less is more.
- Change the inheritance of our own Items. e. g. a SwitchGroupItem should extend a SwitchItem

@seaside1 what do you think?
Are the custom Item generation a special need for something?

**Comment by seaside1** [comment]
Which items should we not generate? I think in the form of consistency that it could be good to generate all or none. Previously before we had the JRuleItems-file, the generated classes were used a lot more. Possibly we could look into not generating custom item classes at all, and only generate the JRuleItems.

Regarding inheritance I guess it depends if it retains more common functionality from JRuleGroupItem rather than switch, it makes sense to extend JRuleGroup.

**Comment by querdenker2k** [comment]
We should generate no Items and just use the JRuleItems fields.
I think it's better to let a group Item extend a "simple" Item, just from the logical point of view. A group Item is a special "simple" Item.

I thought about to remove all the *Value classes and use the OH types, but then decided to not do it just because of the naming (JRule*)

**Comment by seime** [comment]
I'm sure it can be simplified and reworked. 

Also thought about extracting interfaces for both the "standalone" and the "group" version of an item so it can be handled the same way in rules.

For me the essential part here is to have compiler-checkable item/thing/action names and typed methods for sendCommand/postUpdate. I'd even prefer if the rule method event classes could come as a reference to the actual item, not just the itemname. I also love the typed sendCommand/postUpdate methods on the generated JRuleItem classes as it to a certain degree prevents me from sending a non-compatible command to an item (room for improvements here though).

**Comment by querdenker2k** [comment]
> I'm sure it can be simplified and reworked.
> 
> Also thought about extracting interfaces for both the "standalone" and the "group" version of an item so it can be handled the same way in rules.
> 
> For me the essential part here is to have compiler-checkable item/thing/action names and typed methods for sendCommand/postUpdate. I'd even prefer if the rule method event classes could come as a reference to the actual item, not just the itemname. I also love the typed sendCommand/postUpdate methods on the generated JRuleItem classes as it to a certain degree prevents me from sending a non-compatible command to an item (room for improvements here though).

Agree.
There will be intefaces for all Item types and concrete internal implementations of all of them which will be used in the JRuleItems file.
Let the event use the real item is as well a good idea, if it is "possible" i will do it in another pull request.
The sendCommand/postUpdate methods will be available in the interfaces as well (and every interface will just have the valid parameters for these methods). No need for extra generated Item classes

**Comment by seime** [comment]
I think it is possible to extract a list of accepted commands for an item by doing a tiny bit of reflection (look for `getAcceptedTypes()` and `getAcceptedCommandTypes()` in the various XXXItem core classes). Could make this issue a coding task and not an error prone punching task :)

**Comment by seaside1** [comment]
Good discussion. Yes removing the generated items could also remove some code and make things easier and simpler.  I agree that one of the best benefits of JRule is the strict typing, that it is easy to get the rules right without trial and error in openhab. I tend to develop rules much faster and more error prone compare to rules dsl and Jython.

**Comment by querdenker2k** [comment]
https://github.com/seaside1/jrule/pull/85
Ready so far, but some tests have to be added.

**Comment by querdenker2k** [comment]
merged
