### ISSUE TITLE
Remove jar files from git repository

### ISSUE THREAD

**Issue by LumnitzF** [seaside1/jrule#9]
It is generally a bad practive, to store binary files (i.e. jar files) in a git repository, as it will be included in the repo forever. For example see [this](https://vegeta2102.medium.com/why-you-should-not-push-binary-files-to-git-and-what-to-do-if-you-do-29f34692cef0) resource.

A different approach could be to provide the files as [github release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository). As this is based on tags, it could be easier for developers, to identify the actual changes between different versions.

**Comment by seaside1** [comment]
Hi!

You are right, I will try to make this happen.

**Comment by seaside1** [comment]
I've made a proper release, will clean up the repo later on.
