### ISSUE TITLE
ItemName in memberName when using memberOf trigger

### ISSUE THREAD

**Issue by querdenker2k** [seaside1/jrule#93]
Actually the ItemName of the triggered Item is in MemberName even when using memberOf as trigger.
I think this is a bad idea (yes it was my own).
When having multiple triggers, some with memberOf and some without I don't know where to look for the triggered item name.
I would like to put the triggered Itemname inside Itemname and let memberName empty.

@seaside1 @seime What do you think?

**Comment by seaside1** [comment]
I have to come back with this one, could it be an option to do both (itemname and membername)?

**Comment by querdenker2k** [comment]
Of course, this would be ok as well. I will change tomorrow

**Comment by seime** [comment]
@querdenker2k if resolved via #95, please close!
